<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Tema 2 Intervals de confiança | Matemàtiques II</title>
  <meta name="description" content="Apunts Matemàtiques II bookdown::gitbook.">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="Tema 2 Intervals de confiança | Matemàtiques II" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Apunts Matemàtiques II bookdown::gitbook." />
  <meta name="github-repo" content="cescrossello/MatesII" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Tema 2 Intervals de confiança | Matemàtiques II" />
  
  <meta name="twitter:description" content="Apunts Matemàtiques II bookdown::gitbook." />
  

<meta name="author" content="The Matemàtiques II team">


<meta name="date" content="2020-01-16">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="estimacio-puntual.html">

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Bioestadística II</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Presentació</a></li>
<li class="part"><span><b>Part II: Estadística inferencial</b></span></li>
<li class="chapter" data-level="" data-path="tema-0-repas-de-la-distribucio-normal.html"><a href="tema-0-repas-de-la-distribucio-normal.html"><i class="fa fa-check"></i>Tema 0    Repàs de la distribució normal</a><ul>
<li class="chapter" data-level="0.1" data-path="tema-0-repas-de-la-distribucio-normal.html"><a href="tema-0-repas-de-la-distribucio-normal.html#propietats-de-la-distribucio-normal"><i class="fa fa-check"></i><b>0.1</b> Propietats de la distribució normal</a></li>
<li class="chapter" data-level="0.2" data-path="tema-0-repas-de-la-distribucio-normal.html"><a href="tema-0-repas-de-la-distribucio-normal.html#amb-r"><i class="fa fa-check"></i><b>0.2</b> Amb R</a></li>
<li class="chapter" data-level="0.3" data-path="tema-0-repas-de-la-distribucio-normal.html"><a href="tema-0-repas-de-la-distribucio-normal.html#tipificacio"><i class="fa fa-check"></i><b>0.3</b> Tipificació</a></li>
<li class="chapter" data-level="0.4" data-path="tema-0-repas-de-la-distribucio-normal.html"><a href="tema-0-repas-de-la-distribucio-normal.html#intervals-de-referencia"><i class="fa fa-check"></i><b>0.4</b> Intervals de referència</a></li>
<li class="chapter" data-level="0.5" data-path="tema-0-repas-de-la-distribucio-normal.html"><a href="tema-0-repas-de-la-distribucio-normal.html#el-z-score"><i class="fa fa-check"></i><b>0.5</b> El z-score</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="estimacio-puntual.html"><a href="estimacio-puntual.html"><i class="fa fa-check"></i><b>1</b> Estimació puntual</a><ul>
<li class="chapter" data-level="1.1" data-path="estimacio-puntual.html"><a href="estimacio-puntual.html#definicions-basiques"><i class="fa fa-check"></i><b>1.1</b> Definicions bàsiques</a></li>
<li class="chapter" data-level="1.2" data-path="estimacio-puntual.html"><a href="estimacio-puntual.html#mitjana-mostral"><i class="fa fa-check"></i><b>1.2</b> Mitjana mostral</a></li>
<li class="chapter" data-level="1.3" data-path="estimacio-puntual.html"><a href="estimacio-puntual.html#proporcio-mostral"><i class="fa fa-check"></i><b>1.3</b> Proporció mostral</a></li>
<li class="chapter" data-level="1.4" data-path="estimacio-puntual.html"><a href="estimacio-puntual.html#variancia-mostral"><i class="fa fa-check"></i><b>1.4</b> Variància mostral</a></li>
<li class="chapter" data-level="1.5" data-path="estimacio-puntual.html"><a href="estimacio-puntual.html#la-t-de-student"><i class="fa fa-check"></i><b>1.5</b> La t de Student</a></li>
<li class="chapter" data-level="1.6" data-path="estimacio-puntual.html"><a href="estimacio-puntual.html#bons-estimadors"><i class="fa fa-check"></i><b>1.6</b> “Bons” estimadors</a><ul>
<li class="chapter" data-level="1.6.1" data-path="estimacio-puntual.html"><a href="estimacio-puntual.html#estimadors-no-esbiaixats"><i class="fa fa-check"></i><b>1.6.1</b> Estimadors no esbiaixats</a></li>
<li class="chapter" data-level="1.6.2" data-path="estimacio-puntual.html"><a href="estimacio-puntual.html#estimadors-eficients"><i class="fa fa-check"></i><b>1.6.2</b> Estimadors eficients</a></li>
<li class="chapter" data-level="1.6.3" data-path="estimacio-puntual.html"><a href="estimacio-puntual.html#estimadors-maxim-versemblants"><i class="fa fa-check"></i><b>1.6.3</b> Estimadors màxim versemblants</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="estimacio-puntual.html"><a href="estimacio-puntual.html#estimacio-de-poblacions"><i class="fa fa-check"></i><b>1.7</b> Estimació de poblacions</a><ul>
<li class="chapter" data-level="1.7.1" data-path="estimacio-puntual.html"><a href="estimacio-puntual.html#estimacio-de-poblacions-numerades"><i class="fa fa-check"></i><b>1.7.1</b> Estimació de poblacions numerades</a></li>
<li class="chapter" data-level="1.7.2" data-path="estimacio-puntual.html"><a href="estimacio-puntual.html#marca-recaptura"><i class="fa fa-check"></i><b>1.7.2</b> Marca-recaptura</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="intervals-de-confianca.html"><a href="intervals-de-confianca.html"><i class="fa fa-check"></i><b>2</b> Intervals de confiança</a><ul>
<li class="chapter" data-level="2.1" data-path="intervals-de-confianca.html"><a href="intervals-de-confianca.html#definicions-basiques-1"><i class="fa fa-check"></i><b>2.1</b> Definicions bàsiques</a></li>
<li class="chapter" data-level="2.2" data-path="intervals-de-confianca.html"><a href="intervals-de-confianca.html#exemple-interval-de-confianca-del-95-per-a-la-mitjana-duna-variable-aleatoria-normal"><i class="fa fa-check"></i><b>2.2</b> Exemple: Interval de confiança del 95% per a la mitjana d’una variable aleatòria normal</a></li>
<li class="chapter" data-level="2.3" data-path="intervals-de-confianca.html"><a href="intervals-de-confianca.html#interval-de-confianca-per-a-la-mitjana-basat-en-la-t-de-student"><i class="fa fa-check"></i><b>2.3</b> Interval de confiança per a la mitjana basat en la t de Student</a><ul>
<li class="chapter" data-level="" data-path="intervals-de-confianca.html"><a href="intervals-de-confianca.html#la-formula"><i class="fa fa-check"></i>La fórmula</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confianca.html"><a href="intervals-de-confianca.html#algunes-consideracions"><i class="fa fa-check"></i>Algunes consideracions</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confianca.html"><a href="intervals-de-confianca.html#amb-r-1"><i class="fa fa-check"></i>Amb R</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confianca.html"><a href="intervals-de-confianca.html#calcul-de-la-mida-de-la-mostra-per-fixar-lerror"><i class="fa fa-check"></i>Càlcul de la mida de la mostra per fixar l’error</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="intervals-de-confianca.html"><a href="intervals-de-confianca.html#intervals-de-confianca-per-a-proporcions"><i class="fa fa-check"></i><b>2.4</b> Intervals de confiança per a proporcions</a><ul>
<li class="chapter" data-level="" data-path="intervals-de-confianca.html"><a href="intervals-de-confianca.html#metode-exacte-de-clopper-pearson"><i class="fa fa-check"></i>Mètode “exacte” de Clopper-Pearson</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confianca.html"><a href="intervals-de-confianca.html#metode-de-wilson"><i class="fa fa-check"></i>Mètode de Wilson</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confianca.html"><a href="intervals-de-confianca.html#metode-de-laplace"><i class="fa fa-check"></i>Mètode de Laplace</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confianca.html"><a href="intervals-de-confianca.html#mes-exemples"><i class="fa fa-check"></i>Més exemples</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confianca.html"><a href="intervals-de-confianca.html#calcul-de-la-mida-de-la-mostra-per-a-fixar-lerror"><i class="fa fa-check"></i>Càlcul de la mida de la mostra per a fixar l’error</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="intervals-de-confianca.html"><a href="intervals-de-confianca.html#intervals-de-confianca-per-a-la-variancia-duna-variable-normal"><i class="fa fa-check"></i><b>2.5</b> Intervals de confiança per a la variància d’una variable normal</a></li>
<li class="chapter" data-level="2.6" data-path="intervals-de-confianca.html"><a href="intervals-de-confianca.html#poblacions-finites"><i class="fa fa-check"></i><b>2.6</b> “Poblacions finites”</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/cescrossello/Mates-II" target="blank">Publicat amb  bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Matemàtiques II</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="intervals-de-confianca" class="section level1">
<h1><span class="header-section-number">Tema 2</span> Intervals de confiança</h1>
<div id="definicions-basiques-1" class="section level2">
<h2><span class="header-section-number">2.1</span> Definicions bàsiques</h2>
<p>Amb un estimador, estimam el paràmetre amb una certa precisió, que depèn:</p>
<ul>
<li><p>De la variabilitat de la variable aleatòria d’interès</p></li>
<li><p>De la mida de la mostra</p></li>
<li><p>De la variabilitat de l’estimador (que segurament depèn de les dues anteriors)</p></li>
<li><p>Del <strong>nivell de confiança</strong>, o <em>seguretat</em>, de l’estimació: com de segurs volem estar que l’estimació és correcta</p></li>
</ul>
<p><img src="Bioestadistica-II_files/figure-html/Garfield.png" style="display: block; margin: auto;" /></p>
<p>Un <strong>interval de confiança del q%</strong> (abreviadament, un <strong>IC q%</strong>) d’un paràmetre poblacional és un interval obtingut aplicant a una mostra aleatòria simple una fórmula que satisfà la propietat següent:</p>

<div class="rmdimportant">
L’interval obtingut conté el valor del paràmetre poblacional el q% de les vegades que l’aplicam sobre mostres aleatòries simples preses a l’atzar
</div>

<p><em>Tenir una confiança del q%</em> significa doncs que empram una fórmula que encerta el q% de les vegades; o, per ser precisos, el q% de les vegades que l’aplicam bé. Però assumim que un (1-q)% de les vegades que l’aplicam ens equivocam, i no sabem quin és el nostre cas.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-91" class="example"><strong>Exemple 2.1  </strong></span>En un experiment hem mesurat el percentatge d’augment d’alcohol en sang a 40 persones després de prendre 4 canyes de cervesa. La mitjana i la desviació típica mostral d’aquests percentatges d’increment han estat <span class="math inline">\(\overline{x}=41.2\)</span> i <span class="math inline">\(\widetilde{s}=2.1\)</span>. Com veurem a l’Exemple <a href="intervals-de-confianca.html#exm:alcohol1">2.3</a>, un IC 95% per al percentatge d’augment mitjà d’alcohol en sang d’una persona després de beure 4 canyes de cervesa és [40.53, 41.87].</p>
<p>Això significa que estam <em>segurs al 95%</em> que l’augment mitjà d’alcohol en sang d’una persona després de beure 4 canyes de cervesa està entre el 40.53% i el 41.87%, perquè aquest interval l’haurem calculat amb una fórmula que el 95% de les vegades que l’aplicam (bé) dóna un interval que conté la mitjana poblacional que volem estimar. Nosaltres som optimistes i “confiam” estar dins aquest 95% d’encerts.</p>
</div>


<div class="rmdcaution">
<p>No confongueu:</p>
<ul>
<li><p><strong>Interval de referència del q% per a una variable aleatòria</strong>: Interval que conté <em>el valor de la variable aleatòria en un individu</em> amb probabilitat q%.</p></li>
<li><p><strong>Interval de confiança del q% per a un paràmetre</strong>: Interval que conté <em>el valor poblacional del paràmetre de la variable aleatòria</em> “amb probabilitat” q%, en el sentit que l’hem calculat amb una fórmula que dóna un interval que conté el paràmetre el q% de les vegades que l’aplicam a una mostra aleatòria.</p></li>
<li><strong>Interval de referència del q% per a un estimador</strong>: Interval que conté <em>el valor de l’estimador sobre una mostra aleatòria</em> amb probabilitat q%.<br />
</li>
</ul>
</div>

<p>Per exemple:</p>
<ul>
<li><p>Si diem que un <em>interval de referència del 95%</em> per a la concentració d’una proteïna en sèrum en individus sans mesurada en g/dl és [11,16], això significa significa que un 95% dels individus sans tenen una concentració d’aquesta proteïna en sèrum entre 11 i 16 g/dl, o, equivalentment, que un individu sa escollit a l’atzar té, amb un 95% de probabilitat, una concentració d’aquesta proteïna en sèrum entre 11 i 16 g/dl</p></li>
<li><p>Si diem que un <em>interval de confiança del 95%</em> per a la concentració mitjana d’una proteïna en sèrum en individus sans mesurada en g/dl és [11,16], això significa que hem pres una mostra aleatòria de concentracions d’aquesta proteïna en sèrum en individus sans i a partir d’aquesta mostra hem estimat que, amb un 95% de confiança, la concentració mitjana d’aquesta proteïna en sèrum en individus sans està entre 11 i 16 g/dl (i tenim un 95% de confiança en aquest interval perquè l’hem calculat amb una fórmula que dóna un interval que conté la mitjana poblacional un 95% de les vegades que l’empram).</p></li>
<li><p>Si diem que el 95% de les mostres de 100 concentracions d’una determinada proteïna en sèrum en individus sans tenen la mitjana mostral entre 11 i 16, això és un <em>interval de referència del 95% per a la mitjana mostral</em> de mostres de mida 100, no un interval de confiança per a la concentració mitjana poblacional ni un interval de referència per al valor de la concentració en un individu.</p></li>
</ul>
<p>Que un IC q% per a un paràmetre <span class="math inline">\(\theta\)</span> sigui <span class="math inline">\([a,b]\)</span> serveix:</p>
<ul>
<li><p>Per estimar <span class="math inline">\(\theta\)</span> amb aquest marge de <em>confiança</em>: Estam bastant segurs que el valor poblacional de <span class="math inline">\(\theta\)</span> està entre <span class="math inline">\(a\)</span> i <span class="math inline">\(b\)</span> (la fórmula emprada encerta sovint)</p></li>
<li><p>Per poder rebutjar un valor concret de <span class="math inline">\(\theta\)</span> amb aquest marge de <em>confiança</em>: Estam bastant segurs que el valor real de <span class="math inline">\(\theta\)</span> no està ni per sota de <span class="math inline">\(a\)</span> ni per sobre de <span class="math inline">\(b\)</span></p></li>
</ul>
<p><strong>Per exemple:</strong> si un IC 95% per a la <strong>prevalència</strong> <span class="math inline">\(p\)</span> d’una determinada característica en una població (la fracció d’individus que tenen aquesta característica) va de 0.025 a 0.047:</p>
<ul>
<li><p>Estam molt (95%) segurs que <span class="math inline">\(p\in [0.025,0.047]\)</span> (perquè la fórmula emprada per calcular aquest interval encerta en un 95% de les vegades)</p></li>
<li><p>Estam molt segurs que <span class="math inline">\(p&gt;0.02\)</span> (perquè tot l’interval on estam molt segurs que cau el valor real de <span class="math inline">\(p\)</span> està a la dreta de 0.02)</p></li>
<li><p>Estam molt segurs que <span class="math inline">\(p\neq 0.05\)</span> (perquè 0.05 no pertany a l’interval on estam molt segurs que cau el valor real de <span class="math inline">\(p\)</span>)</p></li>
<li><p>Però <em>no estam molt segurs</em> que <span class="math inline">\(p=0.03\)</span>, per molt que <span class="math inline">\(0.03\in [0.025,0.047]\)</span>: estam molt segurs que <span class="math inline">\(p\)</span> està entre 0.025 i 0.047, però no tenim cap seguretat que valgui un valor concret entre aquests límits, només que està entre aquests límits.</p></li>
</ul>
<p>Hi ha dos tipus de mètodes bàsics de càlcul d’IC a partir d’una mostra aleatòria:</p>
<ul>
<li><p><strong>Paramètrics</strong>: Usant alguna fórmula basada en la distribució mostral de l’estimador</p>
<ul>
<li><p>Es basen en teoremes</p></li>
<li><p>Només serveixen si la variable aleatòria <span class="math inline">\(X\)</span> i la mostra aleatòria satisfan (aproximadament) les hipòtesis del teorema</p></li>
</ul></li>
<li><p><strong>No paramètrics</strong>: El més emprat és el <strong>bootstrap</strong>:</p>
<ul>
<li><p>De la mostra, es prenen a l’atzar moltes (~1000) mostres aleatòries simples de la mateixa mida que la mostra, es calcula l’estimador amb cada una d’aquestes mostres i s’usa el vector de resultats per estimar un IC (per exemple, podríem prendre com a IC 95% l’interval entre els quantils 0.025 i 0.975 d’aquest vector)</p></li>
<li><p>Es pot usar sempre (si la mostra és aleatòria)</p></li>
<li><p>Empra un procés aleatori: en cada execució sobre les mateixes dades pot donar un IC diferent</p></li>
</ul></li>
</ul>
</div>
<div id="exemple-interval-de-confianca-del-95-per-a-la-mitjana-duna-variable-aleatoria-normal" class="section level2">
<h2><span class="header-section-number">2.2</span> Exemple: Interval de confiança del 95% per a la mitjana d’una variable aleatòria normal</h2>
<p>Suposem que tenim una variable normal <span class="math inline">\(X\sim N(\mu,\sigma)\)</span>. Volem trobar un IC 95% per a la seva mitjana <span class="math inline">\(\mu\)</span>.
Per calcular-lo, prenem una mostra aleatòria simple de mida <span class="math inline">\(n\)</span>, de mitjana <span class="math inline">\(\overline{X}\)</span> i variància mostral <span class="math inline">\(\widetilde{S}^2_X\)</span>.</p>
<p>Aleshores, sabem que
<span class="math display">\[
T=\frac{\overline{X}-\mu}{\widetilde{S}_{X}/\sqrt{n}}
\]</span>
té distribució t de Student amb <span class="math inline">\(n-1\)</span> graus de llibertat, <span class="math inline">\(t_{n-1}\)</span>.</p>
<p>Si podem trobar <span class="math inline">\(A,B\in \mathbb{R}\)</span> tals que
<span class="math display">\[
P(A\leqslant T\leqslant B)=0.95,
\]</span>
llavors:
<span class="math display">\[
\begin{array}{rl}
0.95 &amp; =P\Bigg(A\leqslant\dfrac{\overline{X}-\mu}{\widetilde{S}_{X}/\sqrt{n}}\leqslant B\Bigg)\\[2ex]
&amp; =P\Bigg(A\cdot \dfrac{\widetilde{S}_X}{\sqrt{n}}\leqslant\overline{X}-\mu \leqslant B\cdot \dfrac{\widetilde{S}_X}{\sqrt{n}}\Bigg)\\[2ex]
&amp; =P\Bigg(-\overline{X}+A\cdot \dfrac{\widetilde{S}_X}{\sqrt{n}}\leqslant-\mu \leqslant-\overline{X}+B\cdot \dfrac{\widetilde{S}_X}{\sqrt{n}}\Bigg)\\[2ex]
&amp; =P\Bigg(\overline{X}-B\cdot \dfrac{\widetilde{S}_X}{\sqrt{n}}\leqslant\mu \leqslant\overline{X}-A\cdot \dfrac{\widetilde{S}_X}{\sqrt{n}}\Bigg)
\end{array}
\]</span></p>
<p>Com que <span class="math inline">\(P(A\leqslant T\leqslant B)=0.95\)</span> significa que per al 95% de les mostres aleatòries simples de mida <span class="math inline">\(n\)</span> el valor de <span class="math inline">\(T\)</span> està entre <span class="math inline">\(A\)</span> i <span class="math inline">\(B\)</span>,
<span class="math display">\[
P\Bigg(\overline{X}-B\cdot \frac{\widetilde{S}_X}{\sqrt{n}}\leqslant\mu \leqslant\overline{X}-A\cdot \frac{\widetilde{S}_X}{\sqrt{n}}\Bigg)=0.95
\]</span>
significa que per al 95% de les mostres aleatòries simples de mida <span class="math inline">\(n\)</span> la <span class="math inline">\(\mu\)</span> cau dins l’interval
<span class="math display">\[
\Bigg[\overline{X}-B\cdot \frac{\widetilde{S}_X}{\sqrt{n}},\ \overline{X}-A\cdot \frac{\widetilde{S}_X}{\sqrt{n}}\Bigg]
\]</span>
Per tant, això serà un IC 95% per a <span class="math inline">\(\mu\)</span>.</p>
<p>Ens falta trobar els <span class="math inline">\(A,B\)</span> tals que <span class="math inline">\(P(A\leqslant T\leqslant B)=0.95\)</span>. Per trobar-los, emprarem <em>quantils de la distribució de <span class="math inline">\(T\)</span></em>. Recordem que si indicam amb <span class="math inline">\(t_{n-1,0.975}\)</span> el 0.975-quantil d’una <span class="math inline">\(t_{n-1}\)</span>, per definició tenim que
<span class="math display">\[
P(T\leqslant t_{n-1,0.975})=0.975
\]</span>
i per la simetria de la <span class="math inline">\(t\)</span>,
<span class="math display">\[
P(T\leqslant-t_{n-1,0.975})=P(T\geqslant t_{n-1,0.975})=0.025
\]</span>
Per tant:
<span class="math display">\[
\begin{array}{l}
P(-t_{n-1,0.975}\leqslant T\leqslant t_{n-1,0.975})\\
\quad =P(T\leqslant t_{n-1,0.975})-P(T\leqslant-t_{n-1,0.975})\\
\quad =0.975-0.025=0.95
\end{array}
\]</span></p>
<p>Així doncs, podem prendre
<span class="math display">\[
A=-t_{n-1,0.975},\quad B=t_{n-1,0.975}
\]</span>
i obtenim:</p>

<div class="rmdimportant">
Si <span class="math inline">\(X\sim N(\mu,\sigma)\)</span>, un IC 95% per a <span class="math inline">\(\mu\)</span> és
<span class="math display">\[
\Bigg[\overline{X}-t_{n-1,0.975}\cdot \frac{\widetilde{S}_X}{\sqrt{n}},\ \overline{X}+t_{n-1,0.975}\cdot\frac{\widetilde{S}_X}{\sqrt{n}}\Bigg]
\]</span>
</div>

<p>L’escriurem
<span class="math display">\[
\overline{X}\pm t_{n-1,0.975}\cdot \frac{\widetilde{S}_X}{\sqrt{n}}
\]</span></p>

<div class="example">
<p><span id="exm:unnamed-chunk-94" class="example"><strong>Exemple 2.2  </strong></span>Fem un experiment per veure que, efectivament, aquesta fórmula “encerta”, en el sentit que conté la <span class="math inline">\(\mu\)</span>, al voltant del 95% de les vegades. Al bloc de codi següent: generam una <em>Població</em> de 10<sup>7</sup> “individus” que segueixen una llei normal estàndard i en calculam la mitjana <code>mu</code>; definim una funció <code>IC</code> que calcula l’IC 95% per a la mitjana <span class="math inline">\(\mu\)</span> amb la fórmula anterior; prenem 200 mostres aleatòries simples de mida 50 de la nostra població i les aplicam aquesta funció, obtenint una matriu <code>M</code> de 200 columnes formades pels dos extrems dels intervals (l’inferior a la primera filera i el superior a la segona filera); finalment, miram quantes vegades hem encertat, és a dir, a quantes columnes de <code>M</code> la mitjana poblacional <code>mu</code> està entre l’entrada de la primera filera i la de la segona.</p>
</div>

<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">42</span>)
Poblacio=<span class="kw">rnorm</span>(<span class="dv">10</span><span class="op">^</span><span class="dv">7</span>)
mu=<span class="kw">mean</span>(Poblacio)
IC=<span class="cf">function</span>(x){
  n=<span class="kw">length</span>(x)
  <span class="kw">mean</span>(x)<span class="op">+</span><span class="kw">qt</span>(<span class="fl">0.975</span>,n<span class="dv">-1</span>)<span class="op">*</span><span class="kw">sd</span>(x)<span class="op">/</span><span class="kw">sqrt</span>(n)<span class="op">*</span><span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>,<span class="dv">1</span>)}
M=<span class="kw">replicate</span>(<span class="dv">200</span>,<span class="kw">IC</span>(<span class="kw">sample</span>(Poblacio,<span class="dv">50</span>,<span class="dt">replace=</span><span class="ot">TRUE</span>)))
Encerts=<span class="kw">length</span>(<span class="kw">which</span>(mu<span class="op">&gt;=</span>M[<span class="dv">1</span>,] <span class="op">&amp;</span><span class="st"> </span>mu<span class="op">&lt;=</span>M[<span class="dv">2</span>,]))
Encerts</code></pre>
<pre><code>## [1] 189</code></pre>
<p>Hem encertat 189 vegades, és a dir, un 94.5% de les vegades. És aproximadament el que esperàvem. Si ho provau amb altres llavors d’aleatorietat obtendreu altres resultats, de vegades millors, de vegades pitjors.</p>
<p>Per veure millor els encerts, dibuixam els intervals en un gràfic, on apareixeran en gris els que encerten i en vermell els que no encerten.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(<span class="dv">1</span>,<span class="dt">type=</span><span class="st">&quot;n&quot;</span>,<span class="dt">xlim=</span><span class="kw">c</span>(<span class="op">-</span><span class="fl">0.8</span>,<span class="fl">0.8</span>),<span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">200</span>),
  <span class="dt">xlab=</span><span class="st">&quot;Valors&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;Repeticions&quot;</span>, <span class="dt">main=</span><span class="st">&quot;200 IC 95%&quot;</span>)
seg.int=<span class="cf">function</span>(i){color=<span class="st">&quot;grey&quot;</span>;
  <span class="cf">if</span>((mu<span class="op">&lt;</span>M[<span class="dv">1</span>,i]) <span class="op">|</span><span class="st"> </span>(mu<span class="op">&gt;</span>M[<span class="dv">2</span>,i])){color=<span class="st">&quot;red&quot;</span>}
  <span class="kw">segments</span>(M[<span class="dv">1</span>,i],i,M[<span class="dv">2</span>,i],i,<span class="dt">col=</span>color,<span class="dt">lwd=</span><span class="dv">2</span>)}
<span class="kw">sapply</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">200</span>,<span class="dt">FUN=</span>seg.int)
<span class="kw">abline</span>(<span class="dt">v=</span>mu,<span class="dt">lwd=</span><span class="dv">2</span>)</code></pre>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-96-1.png" width="480" style="display: block; margin: auto;" /></p>

<div class="rmdcaution">
<strong>Atenció!</strong> De mitjana, un IC <em>q%</em> NO conté el valor real del paràmetre en un <em>(100-q)%</em> de les ocasions.
</div>

<p>Per exemple, de mitjana, un 5% de les vegades que calculam un IC 95%, el paràmetre poblacional no pertany a l’interval obtingut. Per tant, si calculam <span class="math inline">\(n\)</span> IC 95% sobre mostres aleatòries simples independents, el nombre de vegades que l’interval resultant no contendrà el paràmetre poblacional seguirà una distribució binomial <span class="math inline">\(B(n,0.05)\)</span>. El gràfic següent dóna el valor de <span class="math inline">\(P(X\geqslant 1)\)</span> per a una variable aleatòria <span class="math inline">\(X\)</span> de tipus <span class="math inline">\(B(n,0.05)\)</span>, per a <span class="math inline">\(n=0,...,100\)</span>, i per tant la probabilitat que si calculam <span class="math inline">\(n\)</span> IC 95% sobre mostres aleatòries simples independents, almenys un d’ells no contengui el paràmetre poblacional desitjat.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(<span class="dv">1</span><span class="op">-</span><span class="kw">dbinom</span>(<span class="dv">0</span>,<span class="dv">0</span><span class="op">:</span><span class="dv">100</span>,<span class="fl">0.05</span>),<span class="dt">pch=</span><span class="dv">20</span>,<span class="dt">xlab=</span><span class="st">&quot;n&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;Probabilitat&quot;</span>,
     <span class="dt">main=</span><span class="st">&quot;Probabilitat d&#39;algun èxit en una B(n,0.05)&quot;</span>)</code></pre>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-98-1.png" width="480" style="display: block; margin: auto;" /></p>
<p>Tornant a l’IC 95% per a <span class="math inline">\(\mu\)</span> d’una variable normal donat per la fórmula
<span class="math display">\[
\overline{X}\pm t_{n-1,0.975}\cdot \frac{\widetilde{S}_X}{\sqrt{n}}
\]</span>
fixau-vos que:</p>
<ul>
<li><p>Està centrat en <span class="math inline">\(\overline{X}\)</span>, per tant en cada càlcul estarà centrat en la mitjana mostral</p></li>
<li><p>Tal i com l’hem calculat, la probabilitat que <span class="math inline">\(\mu\)</span> caigui fora d’aquest interval es reparteix per igual als dos costats: un 2.5% de les vegades la <span class="math inline">\(\mu\)</span> poblacional estarà a l’esquerra de l’extrem inferior i un 2.5% de les vegades estarà a la dreta de l’extrem superior</p></li>
</ul>

<div class="example">
<p><span id="exm:alcohol1" class="example"><strong>Exemple 2.3  </strong></span>En un experiment hem mesurat el percentatge d’augment d’alcohol en sang a 40 persones després de prendre 4 canyes de cervesa. La mitjana i la desviació típica mostral d’aquests percentatges d’increment han estat
<span class="math display">\[
\overline{x}=41.2,\quad \widetilde{s}=2.1
\]</span>
Per calcular un IC 95% per al percentatge mitjà d’augment, suposarem que la mostra és <em>aleatòria simple</em> i que la variable aleatòria que dóna el percentatge d’augment d’alcohol en sang en una persona després de prendre 4 canyes de cervesa és <em>normal</em>.</p>
</div>

<p>Llavors, com que <span class="math inline">\(t_{n-1,0.975}\)</span>=<code>qt(0.975,39)</code>=2.0227, un IC 95% és
<span class="math display">\[
41.2\pm 2.0227\cdot \frac{2.1}{\sqrt{40}}\Rightarrow 41.2\pm 0.67\Rightarrow [40.53, 41.87]
\]</span></p>
<p>Hem suposat que la variable poblacional “Percentatge d’augment d’alcohol en sang després de prendre 4 canyes de cervesa” segueix una distribució normal. I si no fos normal?</p>
<ul>
<li><p>En aquest cas, com que <span class="math inline">\(n=40\)</span>, és gran pel Teorema <a href="intervals-de-confianca.html#thm:ICmu">2.2</a> de la propera secció l’interval obtingut segueix essent (aproximadament) un interval de confiança del 95% per a <span class="math inline">\(\mu\)</span></p></li>
<li><p>Si <span class="math inline">\(n\)</span> fos petit i <span class="math inline">\(X\)</span> molt diferent d’una normal, no es pot usar aquesta fórmula i cal buscar-se la vida (per exemple, emprar el mètode de <em>bootstrap</em>)</p></li>
</ul>
</div>
<div id="interval-de-confianca-per-a-la-mitjana-basat-en-la-t-de-student" class="section level2">
<h2><span class="header-section-number">2.3</span> Interval de confiança per a la mitjana basat en la t de Student</h2>
<p>A partir d’ara, per tal d’evitar ambigüitats, a les fórmules expressarem el nivell de confiança dels intervals en tant per u, no en tant per cent, i parlarem d’intervals de confiança de nivell de confiança <span class="math inline">\(q\)</span>, amb <span class="math inline">\(q\)</span> entre 0 i 1, en lloc d’intervals de confiança del <span class="math inline">\(100q\%\)</span>. És a dir, per exemple, els intervals de confiança del 95% seran intervals de confiança de nivell de confiança 0.95.</p>
<div id="la-formula" class="section level3 unnumbered">
<h3>La fórmula</h3>
<p>El mateix argument que abans, canviant 0.95 per <span class="math inline">\(q\)</span> dóna:</p>

<div class="theorem">
<span id="thm:unnamed-chunk-99" class="theorem"><strong>Teorema 2.1  </strong></span>Si <span class="math inline">\(X\sim N(\mu,\sigma)\)</span> i prenem una mostra aleatòria simple de mida <span class="math inline">\(n\)</span>, un IC de nivell de confiança <span class="math inline">\(q\)</span> (en tant per u) per a <span class="math inline">\(\mu\)</span> és
<span class="math display">\[
\overline{X}\pm t_{n-1,(1+q)/2}\cdot \frac{\widetilde{S}_X}{\sqrt{n}}
\]</span>
</div>

<p>Fixau-vos que als IC 95%, <span class="math inline">\(q=0.95\)</span> i per tant <span class="math inline">\((1+q)/2=1.95/2=0.975\)</span>.</p>
<p>Usant el Teorema Central del Límit i algunes aproximacions, tenim el següent resultat:</p>

<div class="theorem">
<span id="thm:ICmu" class="theorem"><strong>Teorema 2.2  </strong></span>Sigui <span class="math inline">\(X\)</span> una variable aleatòria qualsevol de mitjana poblacional <span class="math inline">\(\mu\)</span>. Suposem que prenem una mostra aleatòria simple de <span class="math inline">\(X\)</span> de mida <span class="math inline">\(n\)</span> gran (diguem, de 40 o més elements). Llavors, un IC de nivell de confiança <span class="math inline">\(q\)</span> per a <span class="math inline">\(\mu\)</span> és aproximadament
<span class="math display">\[
\overline{X}\pm t_{n-1,(1+q)/2}\cdot \frac{\widetilde{S}_X}{\sqrt{n}}
\]</span>
</div>

<p>L’aproximació del teorema anterior és millor com més gran sigui <span class="math inline">\(n\)</span> o com més propera a una normal sigui la variable poblacional <span class="math inline">\(X\)</span>.</p>
En resum:

<div class="rmdimportant">
Podem emprar la fórmula per a l’IC de nivell de confiança <span class="math inline">\(q\)</span> per a la mitjana poblacional basada en la t de Student
<span class="math display">\[
\overline{X}\pm t_{n-1,(1+q)/2}\cdot \frac{\widetilde{S}_X}{\sqrt{n}}
\]</span>
quan la variable poblacional és normal o quan la mostra aleatòria simple és gran.
</div>


<div class="example">
<p><span id="exm:RXprint" class="example"><strong>Exemple 2.4  </strong></span>L’empresa <em>RX-print</em> ofereix una impressora de radiografies d’altíssima qualitat. En la seva publicitat afirma que els seus
cartutxos imprimeixen una mitjana de 500 radiografies amb l’especificació:</p>
<blockquote>
<p>Dades tècniques: Mostra de mida <span class="math inline">\(n=25\)</span>, població suposada normal, nivell de confiança del 90%</p>
</blockquote>
</div>

<p>Uns radiòlegs desitgen comprovar aquestes afirmacions i prenen una mostra de cartutxos a l’atzar de mida <span class="math inline">\(n=25\)</span>, obtenint una mitjana de <span class="math inline">\(\overline{x}=518\)</span> radiografies i una desviació típica mostral <span class="math inline">\(\widetilde{s}=39.9\)</span>.</p>
<p>Amb aquesta mostra, la mitjana poblacional anunciada pel fabricant cau dins l’interval de confiança del 90%?</p>
<p>La variable aleatòria d’interès és <span class="math inline">\(X\)</span> és “Prenem un cartutxo d’aquesta empresa i miram el nombre de radiografies que permet imprimir”, de mitjana <span class="math inline">\(\mu\)</span> per a la qual volem calcular un IC 90%. Suposarem que la variable <span class="math inline">\(X\)</span> és normal, perquè l’empresa ho suposa a les dades tècniques. Per tant podem emprar la fórmula
<span class="math display">\[
\overline{x}\pm t_{n-1,(q+1)/2} \frac{\widetilde{s}}{\sqrt{n}}
\]</span>
on <span class="math inline">\(n=25\)</span>, <span class="math inline">\(\overline{x}=518\)</span>, <span class="math inline">\(\widetilde{s}=39.9\)</span>, <span class="math inline">\(q=0.9\)</span>, <span class="math inline">\((q+1)/2=0.95\)</span> i <span class="math inline">\(t_{24,0.95}\)</span>=<code>qt(0.95,24)</code><span class="math inline">\(=1.71\)</span>.</p>
<p>Operant:
<span class="math display">\[
518\pm 1.71\times \frac{39.9}{\sqrt{25}}\Rightarrow 
518\pm 13.65\Rightarrow
[504.35,531.65]
\]</span>
No conté el 500 (en benefici del consumidor: tenim un 95% de seguretat que el nombre mitjà de radiografies per cartutxo està en realitat entre 504.35 i 531.65).</p>

<div class="example">
<p><span id="exm:RXprint2" class="example"><strong>Exemple 2.5  </strong></span>A l’exemple anterior hem suposat que la variable aleatòria era normal. Què passaria si no ho fos?</p>
</div>

<p>Com que <span class="math inline">\(n=25\)</span> no és prou gran, no podríem aplicar la fórmula de l’IC basada en la t de Student. Emprarem el mètode del <em>bootstrap</em>, per a la qual cosa necessitam tenir les dades originals, i no només els seus estadístics. Tenim aquestes dades en el vector <code>Radios</code> següent:</p>
<pre class="sourceCode r"><code class="sourceCode r">Radios=<span class="kw">c</span>(<span class="dv">485</span>,<span class="dv">511</span>,<span class="dv">509</span>,<span class="dv">509</span>,<span class="dv">561</span>,<span class="dv">529</span>,<span class="dv">458</span>,<span class="dv">532</span>,<span class="dv">545</span>,<span class="dv">546</span>,
        <span class="dv">503</span>,<span class="dv">577</span>,<span class="dv">547</span>,<span class="dv">477</span>,<span class="dv">507</span>,<span class="dv">548</span>,<span class="dv">480</span>,<span class="dv">444</span>,<span class="dv">461</span>,<span class="dv">573</span>,
        <span class="dv">513</span>,<span class="dv">604</span>,<span class="dv">542</span>,<span class="dv">501</span>,<span class="dv">488</span>)
<span class="kw">mean</span>(Radios)</code></pre>
<pre><code>## [1] 518</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sd</span>(Radios)</code></pre>
<pre><code>## [1] 39.89987</code></pre>
<p>Prenem 5000 mostres aleatòries simples de mida 25 (la mateixa mida que el conjunt de dades original) de les dades i calculam la mitjana de cada mostra; fixam la llavor d’aleatorietat perquè el càlcul sigui reproduïble:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">100</span>)
Simulacions=<span class="kw">replicate</span>(<span class="dv">5000</span>,<span class="kw">mean</span>(<span class="kw">sample</span>(Radios,<span class="dv">25</span>,<span class="dt">rep=</span><span class="ot">TRUE</span>)))</code></pre>
<p>Ara prenem com a IC 90% l’interval que va del quantil 0.05 al quantil 0.95 d’aquest vector de mitjanes:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">quantile</span>(Simulacions,<span class="kw">c</span>(<span class="fl">0.05</span>,<span class="fl">0.95</span>))</code></pre>
<pre><code>##     5%    95% 
## 504.96 530.92</code></pre>
<p>Obtenim l’interval [504.96,530.92]: amb la fórmula basada en la t de Student, havíem obtingut l’interval [504.35,531.65].</p>
</div>
<div id="algunes-consideracions" class="section level3 unnumbered">
<h3>Algunes consideracions</h3>
<p>Observau que l’estructura de l’IC de nivell de confiança <span class="math inline">\(q\)</span> per a <span class="math inline">\(\mu\)</span> donat al Teorema <a href="intervals-de-confianca.html#thm:ICmu">2.2</a>
<span class="math display" id="eq:ICMgral">\[\begin{align}
&amp; \text{estimador}\nonumber\\
&amp; \qquad \pm \frac{1+q}{2}\text{-quantil de la distr. mostral}\times \text{error típic de l&#39;estimació}
\tag{2.1}
\end{align}\]</span></p>
<p>Aquesta estructura és molt típica (però, com veurem, no tots els IC paramètrics tenen aquesta forma) i satisfà que:</p>
<ul>
<li><p>L’IC està centrat en el valor de l’estimador</p></li>
<li><p>La “probabilitat d’equivocar-se” es reparteix per igual als dos costats de l’interval: una fracció <span class="math inline">\(q/2\)</span> de les vegades el paràmetre estarà a l’esquerra de l’extrem inferior i una fracció <span class="math inline">\(q/2\)</span> de les vegades estarà a la dreta de l’extrem superior</p></li>
</ul>
<p>A més, tenim que:</p>
<ul>
<li><p>Per a una mateixa mostra i una mateixa fórmula (paramètrica) per calcular l’IC, si el nivell de confiança creix, l’IC s’eixampla</p>
<p>Això és general, per a tots els intervals de confiança paramètrics. La idea intuitiva és que, per estar més segurs que un interval conté un valor, l’interval ha de ser més ample. A un IC amb l’estructura <a href="intervals-de-confianca.html#eq:ICMgral">(2.1)</a>, el motiu matemàtic és que si <span class="math inline">\(q\)</span> creix, el quantil (1+<span class="math inline">\(q\)</span>)/2 de la distribució mostral creix.</p>
<p>Per exemple, a l’Exemple <a href="intervals-de-confianca.html#exm:alcohol1">2.3</a>, teníem <span class="math inline">\(n=40\)</span>, <span class="math inline">\(\overline{x}=41.2\)</span> i <span class="math inline">\(\widetilde{s}=2.1\)</span>:</p>
<ul>
<li><p>L’IC 95% té <span class="math inline">\(q=0.95\)</span>, per tant <span class="math inline">\(t_{n-1,(1+q)/2}=t_{39,0.975}=2.02\)</span>, i donava
<span class="math display">\[
IC:\ 41.2\pm 2.02\cdot \frac{2.1}{\sqrt{40}}\Rightarrow 41.2\pm 0.67
\]</span></p></li>
<li><p>L’IC 99% té <span class="math inline">\(q=0.99\)</span>, per tant <span class="math inline">\(t_{n-1,(1+q)/2}=t_{39,0.995}=2.71\)</span>, i dóna
<span class="math display">\[
IC:\ 41.2\pm 2.71\cdot \frac{2.1}{\sqrt{40}}\Rightarrow 41.2\pm 0.9
\]</span>
més ample</p></li>
</ul></li>
<li><p>Però si canviam de mostra (o de fórmula, si n’hi ha més d’una) per calcular l’IC, pot passar qualsevol cosa.</p></li>
</ul>
</div>
<div id="amb-r-1" class="section level3 unnumbered">
<h3>Amb R</h3>
<p>La funció</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(X,<span class="dt">conf.level=</span>...)<span class="op">$</span>conf.int</code></pre>
<p>calcula l’interval de confiança basat en la t de Student per a la <span class="math inline">\(\mu\)</span> de la variable aleatòria de la que el vector <code>X</code> n’és una mostra. El paràmetre <code>conf.level</code> permet especificar el nivell de confiança (en tant per u). El seu valor per defecte és 0.95, així que per calcular un IC 95% no cal especificar-lo.</p>
<p>Per exemple, l’IC 90% del vector de nombres de radiografies de l’Exemple <a href="intervals-de-confianca.html#exm:RXprint">2.4</a> es calcularia amb</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(Radios,<span class="dt">conf.level=</span><span class="fl">0.9</span>)<span class="op">$</span>conf.int</code></pre>
<pre><code>## [1] 504.3472 531.6528
## attr(,&quot;conf.level&quot;)
## [1] 0.9</code></pre>
</div>
<div id="calcul-de-la-mida-de-la-mostra-per-fixar-lerror" class="section level3 unnumbered">
<h3>Càlcul de la mida de la mostra per fixar l’error</h3>
<p>Recordem que l’IC q% per a <span class="math inline">\(\mu\)</span> basat en la t de Student
<span class="math display">\[
\overline{X}\pm t_{n-1,(1+q)/2}\cdot \frac{\widetilde{S}_X}{\sqrt{n}}
\]</span>
és simètric i centrat en <span class="math inline">\(\overline{X}\)</span>. La seva <strong>amplada</strong> és la diferència entre els seus extrems
<span class="math display">\[
2t_{n-1,(1+q)/2}\times \frac{\widetilde{S}_X}{\sqrt{n}}
\]</span></p>
<p>El <strong>marge d’error</strong> (<strong>error</strong>, <strong>precisió</strong>) <span class="math inline">\(M\)</span> en l’estimació de <span class="math inline">\(\mu\)</span> per mitjà d’aquest IC é el que sumam i restam a <span class="math inline">\(\overline{X}\)</span> per obtenir l’interval, és a dir, la meitat de la seva amplada:
<span class="math display">\[
M=t_{n-1,(1+q)/2}\times \frac{\widetilde{S}_X}{\sqrt{n}}
\]</span></p>
<p>Una pregunta típica a l’hora de planejar un experiment és quina ha de ser la mida de la mostra que hem de prendre perquè el marge d’error sigui com a màxim un cert valor desitjat <span class="math inline">\(M_{max}\)</span>. És a dir, volem trobar la <span class="math inline">\(n\)</span> més petita tal que
<span class="math display">\[
t_{n-1,(1+q)/2}\times \frac{\widetilde{S}_X}{\sqrt{n}}\leqslant M_{max}.
\]</span>
Però fixau-vos que en aquesta desigualtat la <span class="math inline">\(n\)</span> hi apareix al quantil i a l’error típic, i a més la <span class="math inline">\(\widetilde{S}_X\)</span> depèn de la mostra. El que farem per respondre la pregunta serà fer algunes trampes:</p>
<ul>
<li><p>Aproximarem la t de Student per una normal estàndard (ja que segurament la <span class="math inline">\(n\)</span> haurà de ser gran):
<span class="math display">\[
t_{n-1,(1+q)/2}\rightsquigarrow z_{(1+q)/2} 
\]</span></p></li>
<li><p>Estimarem el valor de <span class="math inline">\(\widetilde{S}_X\)</span> mitjançant la desviació típica mostral <span class="math inline">\(\widetilde{S}_0\)</span> d’una <strong>prova pilot</strong> (una experiment anterior, realitzat per nosaltres o per qualcú altre amb una mostra petita)</p></li>
<li><p>D’aquesta manera, aproximam l’error <span class="math inline">\(M\)</span> per mitjà de
<span class="math display">\[
M\approx z_{(1+q)/2}\times \frac{\widetilde{S}_0}{\sqrt{n}}
\]</span></p></li>
<li><p>I ara si imposam que <span class="math inline">\(M\leqslant M_{max}\)</span>, ja podem aïllar la <span class="math inline">\(n\)</span>:</p></li>
</ul>
<p><span class="math display">\[
z_{(1+q)/2}\times \frac{\widetilde{S}_0}{\sqrt{n}}\leqslant M_{max}\Longrightarrow
n\geqslant\left(\frac{ z_{(1+q)/2}\cdot \widetilde{S}_0}{M_{max}}
\right)^2
\]</span></p>
<p>En resum:</p>

<div class="theorem">
<p><span id="thm:unnamed-chunk-106" class="theorem"><strong>Teorema 2.3  </strong></span>Per estimar la <span class="math inline">\(\mu\)</span> amb nivell de confiança <span class="math inline">\(q\)</span> amb un marge d’error com a màxim <span class="math inline">\(M_{max}\)</span> mitjançant la fórmula basada en la t de Student, prendrem una mostra de mida <span class="math inline">\(n \geqslant( z_{(1+q)/2}\cdot \widetilde{S}_0/M_{max})^2\)</span>, on <span class="math inline">\(\widetilde{S}_0\)</span> és la desviació típica mostral obtinguda en una estimació anterior de <span class="math inline">\(\mu\)</span> (en una <em>prova pilot</em>).</p>
</div>

<p>Naturalment, quan després prenguem una mostra de mida <span class="math inline">\(n\)</span> calculada d’aquesta manera, pot passar qualsevol cosa, ja que hem emprat els resultats d’una mostra aleatòria per estimar la desviació típica d’una altra mostra i a més hem aproximat els quantils de la t de Student per els d’una normal estàndard, que són més petits. Però almenys haurem fet tot el que haurem pogut per fitar l’error dins el marge desitjat.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-107" class="example"><strong>Exemple 2.6  </strong></span>A l’Exemple <a href="intervals-de-confianca.html#exm:alcohol1">2.3</a>, hem emprat una mostra de <span class="math inline">\(n=40\)</span> persones, amb <span class="math inline">\(\overline{x}=41.2\)</span> i <span class="math inline">\(\widetilde{s}=2.1\)</span>, i l’error ha estat
<span class="math display">\[
t_{0.975,39}\cdot \frac{2.1}{\sqrt{40}}=0.67
\]</span>
Quin és el nombre mínim de persones que hauríem hagut d’emprar per obtenir un IC 95% amb un error de (com màxim) 0.5?</p>
</div>

<p>Empram l’exemple com a prova pilot:
<span class="math display">\[
n\geqslant\left(\frac{ z_{(1+q)/2}\cdot \widetilde{s}}{M_{max}} \right)^2=
\left(\frac{1.96\cdot 2.1}{0.5}
\right)^2=67.77
\]</span></p>
<p>El valor de <span class="math inline">\(n\)</span> més petit que satisfà aquesta condició és 68, per tant aquest és el nombre mínim de persones que hauríem hagut d’emprar per esperar obtenir un IC 95% amb un error de (com màxim) 0.5.</p>
</div>
</div>
<div id="intervals-de-confianca-per-a-proporcions" class="section level2">
<h2><span class="header-section-number">2.4</span> Intervals de confiança per a proporcions</h2>
<p>Suposem que tenim una variable Bernoulli <span class="math inline">\(X\)</span> amb probabilitat d’èxit <span class="math inline">\(p_X\)</span> desconeguda. Volem calcular un IC per a <span class="math inline">\(p_X\)</span>.
Per fer-ho, prenem una mostra aleatòria simple de <span class="math inline">\(X\)</span> de mida <span class="math inline">\(n\)</span>, amb nombre d’èxits <span class="math inline">\(x\)</span> i per tant proporció mostral d’èxits <span class="math inline">\(\widehat{p}_{X}=x/n\)</span></p>
<p>Explicarem tres mètodes per calcular aquest IC:</p>

<div class="rmdimportant">
<ul>
<li><p>El <strong>mètode exacte de Clopper-Pearson</strong>, que es pot aplicar sempre però sol donar intervals de confiança més amples del necessari.</p></li>
<li><p>El <strong>mètode aproximat de Wilson</strong>, que es pot emprar quan la mostra és gran, posem de mida 40 o més, i es basa en el fet que, pel Teorema Central del Límit, la proporció mostral de mostres aleatòries simples segueix una distribució aproximadament normal.</p></li>
<li>El <strong>mètode aproximat de Laplace</strong>, que és una simplificació del mètode de Wilson, però només es pot emprar quan la mostra és bastant més gran, posem de mida 100 o més, i la proporció mostral <span class="math inline">\(\widehat{p}_{X}\)</span> no és molt propera a 0 o a 1. És el mètode més clàssic i conegut.</li>
</ul>
</div>

<div id="metode-exacte-de-clopper-pearson" class="section level3 unnumbered">
<h3>Mètode “exacte” de Clopper-Pearson</h3>
<p>Aquest mètode es basa en el fet que el nombre d’èxits <span class="math inline">\(x\)</span> en mostres aleatòries simples de mida <span class="math inline">\(n\)</span> de <span class="math inline">\(X\)</span> segueix una distribució binomial <span class="math inline">\(B(n,p_X)\)</span>. Raonant de manera similar a com obteníem l’interval per a <span class="math inline">\(\mu\)</span> basat en la t de Student (us estalviarem els detalls) arribam a la fórmula següent:</p>

<div class="theorem">
<p><span id="thm:unnamed-chunk-109" class="theorem"><strong>Teorema 2.4  </strong></span>Un IC de nivell de confiança <span class="math inline">\(q\)</span> per a <span class="math inline">\(p_X\)</span> és <span class="math inline">\([p_0,p_1]\)</span>, on</p>
<ul>
<li><p><span class="math inline">\(p_0\)</span> és la solució de l’equació
<span class="math display">\[
\sum_{k=x}^n\binom{n}{k}p_0^k(1-p_0)^{n-k}= \frac{1-q}{2}
\]</span></p></li>
<li><span class="math inline">\(p_1\)</span> és la solució de l’equació
<span class="math display">\[
\sum_{k=0}^x\binom{n}{k}p_1^k(1-p_1)^{n-k}= \frac{1-q}{2}
\]</span>
</div></li>
</ul>
<p>Calcular a mà aquest interval és intractable, i en general dóna més ample del necessari (degut a la natura discreta de la distribució binomial, que només pren valors nombres naturals), però es pot emprar amb mostres aleatòries simples de qualsevol mida ja que empra que el nombre d’èxits <span class="math inline">\(x\)</span> en mostres aleatòries simples de mida <span class="math inline">\(n\)</span> de <span class="math inline">\(X\)</span> segueix una distribució binomial i això sempre és veritat.</p>
<p>Per calcular-lo amb R, podeu emprar la funció del paquet <strong>epitools</strong></p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">binom.exact</span>(x,n,<span class="dt">conf.level=</span>...)</code></pre>
<p>on <code>x</code>és el nombre d’èxits, <code>n</code> la mida de la mostra, i <code>conf.level</code> el nivell de confiança en tant per u, que per defecte val 0.95.</p>

<div class="example">
<p><span id="exm:CP1" class="example"><strong>Exemple 2.7  </strong></span>De 10 pacients tractats amb un medicament, 2 s’han curat. Quin seria un IC 95% per a la proporció <em>p</em> de pacients que aquest medicament cura?</p>
</div>

<p>Emprarem el mètode de Clopper-Pearson</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(epitools)
<span class="kw">round</span>(<span class="kw">binom.exact</span>(<span class="dv">2</span>,<span class="dv">10</span>),<span class="dv">3</span>)</code></pre>
<pre><code>##   x  n proportion lower upper conf.level
## 1 2 10        0.2 0.025 0.556       0.95</code></pre>
<p>Dóna [0.025,0.556].</p>
<p>L’interval de Clopper-Pearson té l’inconvenient que,en general, no està centrat en <span class="math inline">\(\widehat{p}_{X}\)</span>. Per exemple, el centre de l’interval anterior és <span class="math inline">\((0.025+0.556)/2= 0.29\)</span>, diferent de <span class="math inline">\(\widehat{p}_X=0.2\)</span></p>
</div>
<div id="metode-de-wilson" class="section level3 unnumbered">
<h3>Mètode de Wilson</h3>
<p>Suposem ara que prenem una mostra aleatòria simple de <span class="math inline">\(X\)</span> de mida <span class="math inline">\(n\)</span> gran (posem, de 40 o més subjectes) i proporció mostral d’èxits <span class="math inline">\(\widehat{p}_{X}\)</span>. En aquestes condicions, pel Teorema Central del Límit,
<span class="math display">\[
Z=\dfrac{\widehat{p}_{X}-p_X}
{\sqrt{\frac{p_X(1-p_X)}{n}}}\approx N(0,1)
\]</span>
Per tant
<span class="math display">\[
P\Big(-z_{(1+q)/2}\leqslant\dfrac{\widehat{p}_{X}-p_X}
{\sqrt{\frac{p_X(1-p_X)}{n}}}\leqslant z_{(1+q)/2}\Big)=q
\]</span></p>
<p>Aïllant <span class="math inline">\(p_X\)</span> obtenim:</p>

<div class="theorem">
<span id="thm:unnamed-chunk-112" class="theorem"><strong>Teorema 2.5  </strong></span>Si la mida <span class="math inline">\(n\)</span> de la mostra és gran, un IC de nivell de confiança <span class="math inline">\(q\)</span> per a <span class="math inline">\(p_X\)</span> és (aproximadament):
<span class="math display">\[
\frac{\widehat{p}_{X}+\frac{z_{(1+q)/{2}}^2}{2n}\pm z_{(1+q)/{2}}\sqrt{\frac{\widehat{p}_{X}(1-\widehat{p}_{X})}{n}+\frac{z_{(1+q)/{2}}^2}{4n^2}}}{1+\frac{z_{(1+q)/{2}}^2}{n}}
\]</span>
</div>

<p>Amb R es calcula amb la funció</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">binom.wilson</span>(x,n,<span class="dt">conf.level=</span>...)</code></pre>
<p>del paquet <strong>epitools</strong>, amb la mateixa sintaxi que <code>binom.exact</code>. Aquest interval també té l’inconvenient que, si us hi fixau, no està centrat en <span class="math inline">\(\widehat{p}_{X}\)</span>: el seu centre és <span class="math inline">\(\big(\widehat{p}_{X}+z_{(1+q)/{2}}^2/(2n)\big)/(1+z_{(1+q)/{2}}^2/{n})\)</span>.</p>
</div>
<div id="metode-de-laplace" class="section level3 unnumbered">
<h3>Mètode de Laplace</h3>
<p>Suposem finalment que prenem una mostra aleatòria simple de <span class="math inline">\(X\)</span> de mida <span class="math inline">\(n\)</span> més gran i <span class="math inline">\(\widehat{p}_{X}\)</span> enfora de 0 i 1. Per fixar idees, suposem que
<span class="math display">\[
n\geqslant 100,\ n\widehat{p}_{X}\geqslant 10,\  n(1-\widehat{p}_{X})\geqslant 10
\]</span>
En aquest cas, a la fórmula de l’interval de Wilson podem suposar que els termes <span class="math inline">\(z_{(1+q)/{2}}^2/n\)</span> són (aproximadament) 0 i obtenim la fórmula següent:</p>

<div class="theorem">
<span id="thm:unnamed-chunk-114" class="theorem"><strong>Teorema 2.6  </strong></span>En les condicions explicades, un IC de nivell de confiança <span class="math inline">\(q\)</span> per a <span class="math inline">\(p_X\)</span> és (aproximadament):
<span class="math display">\[
\widehat{p}_{X}\pm z_{(q+1)/2}\sqrt{\frac{\widehat{p}_{X}
(1-\widehat{p}_{X})}{n}}
\]</span>
</div>

<p>Amb R es calcula amb la funció</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">binom.approx</span>(x,n,<span class="dt">conf.level=</span>...)</code></pre>
<p>del paquet <strong>epitools</strong>, amb la mateixa sintaxi que <code>binom.exact</code>. Aquesta fórmula és la més popular, amb més de 200 anys de rodatge.</p>

<div class="rmdnote">
Us heu de saber la fórmula de Laplace, no cal saber les fórmules dels altres dos intervals.
</div>

</div>
<div id="mes-exemples" class="section level3 unnumbered">
<h3>Més exemples</h3>

<div class="example">
<p><span id="exm:unnamed-chunk-117" class="example"><strong>Exemple 2.8  </strong></span>En una mostra aleatòria de 500 famílies amb nins en edat escolar es va trobar que 340 introduïen fruita de forma diària en la dieta dels seus fills. A partir d’aquestes dades, volem calcular un interval de confiança del 95% per a la proporció real de famílies d’aquesta ciutat amb nins en edat escolar que incorporen fruita fresca de forma diària en la dieta dels seus fills.</p>
</div>

<p>Diguem <span class="math inline">\(X\)</span> a la variable aleatòria “Prenem una família amb nins en edat escolar i miram si inclou diàriament fruita a la dieta dels fills”. És Bernoulli, digem <span class="math inline">\(p_X\)</span> a la seva probabilitat d’èxit: la probabilitat que una família amb nins en edat escolar inclogui diàriament fruita a la dieta dels fills. Cercam un interval de confiança del 95% per a <span class="math inline">\(p_X\)</span></p>
<p>Com que <span class="math inline">\(n=500\geqslant 100\)</span>, <span class="math inline">\(n\widehat{p}_X=340\geqslant 10\)</span> i <span class="math inline">\(n(1-\widehat{p}_X)=160\geqslant 10\)</span>, podem emprar la fórmula de Laplace
<span class="math display">\[
\widehat{p}_{X}\pm z_{(q+1)/2}\sqrt{\frac{\widehat{p}_{X}
(1-\widehat{p}_{X})}{n}}
\]</span>
amb <span class="math inline">\(n=500\)</span>, <span class="math inline">\(\widehat{p}_{X}=340/500=0.68\)</span> i <span class="math inline">\(z_{(q+1)/2}=z_{0.975}=1.96\)</span>.
Dóna
<span class="math display">\[
0.68\pm 1.96\sqrt{\frac{0.68(1-0.68)}{500}}\Rightarrow [0.639,0.721]
\]</span></p>
<p>Amb R:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">round</span>(<span class="kw">binom.approx</span>(<span class="dv">340</span>,<span class="dv">500</span>), <span class="dv">3</span>)</code></pre>
<pre><code>##     x   n proportion lower upper conf.level
## 1 340 500       0.68 0.639 0.721       0.95</code></pre>
<p>Amb els altres mètodes, que també podríem aplicar en aquest cas, obtenim els intervals:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">round</span>(<span class="kw">binom.exact</span>(<span class="dv">340</span>,<span class="dv">500</span>),<span class="dv">3</span>)</code></pre>
<pre><code>##     x   n proportion lower upper conf.level
## 1 340 500       0.68 0.637 0.721       0.95</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">round</span>(<span class="kw">binom.wilson</span>(<span class="dv">340</span>,<span class="dv">500</span>),<span class="dv">3</span>)</code></pre>
<pre><code>##     x   n proportion lower upper conf.level
## 1 340 500       0.68 0.638 0.719       0.95</code></pre>
<p>Quan podem calcular més d’un interval per a <span class="math inline">\(p_X\)</span>, quin calculam?</p>
<p>D’entrada cal dir que si podem calcular més d’un interval, segurament donaran molt parescuts, com heu pogut comprovar a l’exemple anterior. Però en tot cas, si podeu triar, heu de tenir en compte que:</p>
<ul>
<li>L’interval de Clopper-Pearson és exacte, no empra cap aproximació, però:
<ul>
<li>Tendeix a donar un interval més ample del necessari</li>
<li>No està centrat en la proporció mostral</li>
<li>Només és un interval “exacte” si la mostra és aleatòria simple, cosa que gairebé sempre serà fals (com a molt, serà “aproximadament” aleatòria simple)</li>
<li>Com que fins fa poc no es podia calcular, no és molt popular</li>
</ul></li>
<li><p>L’interval de Wilson és aproximat, fa servir l’aproximació a la normal donada pel Teorema Central del Límit. Això no és un gran emperò, pequè tanmateix segurament la mostra serà com a molt “aproximadament” aleatòria simple. Ara bé, tampoc no està centrat en la proporció mostral</p></li>
<li>L’interval de Laplace és <em>molt</em> aproximat, però:
<ul>
<li>Forma part de la cultura general del científic, tothom el coneix</li>
<li>És l’únic centrat en la proporció mostral</li>
</ul></li>
</ul>

<div class="example">
<p><span id="exm:unnamed-chunk-120" class="example"><strong>Exemple 2.9  </strong></span>En un assaig d’un nou tractament de quimioteràpia, en una mostra de <span class="math inline">\(n\)</span> malalts tractats, cap desenvolupà càncer testicular com a efecte secundari. Quin seria un interval de confiança al 95% per a la proporció de malalts tractats amb aquesta quimio que desenvolupen càncer testicular?</p>
</div>

<p>Per calcular-lo podem emprar el mètode de Clopper-Pearson, i si <span class="math inline">\(n\)</span> és gran, podem emprar el mètode de Wilson. No podem emprar la fórmula de Laplace, perquè <span class="math inline">\(\widehat{p}_X=0\)</span>.</p>
<p>Pel que fa a Clopper-Pearson, aquest és un dels pocs casos que admeten solució analítica senzilla: dóna l’interval
<span class="math display">\[
\Big[0,1-\Big(\frac{1-q}{2}\Big)^{1/n}\Big]
\]</span>
que, si <span class="math inline">\(q=0.95\)</span>, queda
<span class="math display">\[
[0,1-0.025^{1/n}].
\]</span>
Per exemple, si <span class="math inline">\(n=40\)</span></p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">binom.exact</span>(<span class="dv">0</span>,<span class="dv">30</span>)</code></pre>
<pre><code>##   x  n proportion lower     upper conf.level
## 1 0 30          0     0 0.1157033       0.95</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="dv">1</span><span class="fl">-0.025</span><span class="op">^</span>(<span class="dv">1</span><span class="op">/</span><span class="dv">30</span>)</code></pre>
<pre><code>## [1] 0.1157033</code></pre>
<p>Si podem emprar el mètode de Wilson, la fórmula
<span class="math display">\[
\frac{\widehat{p}_{X}+\frac{z_{(q+1)/2}^2}{2n}\pm z_{(q+1)/2}\sqrt{\frac{\widehat{p}_{X}(1-\widehat{p}_{X})}{n}+\frac{z_{(q+1)/2}^2}{4n^2}}}{1+\frac{z_{(q+1)/2}^2}{n}}
\]</span>
amb <span class="math inline">\(\widehat{p}_{X}=0\)</span> i <span class="math inline">\(z_{(1+q)/2}=1.96\)</span> dóna
<span class="math display">\[
\frac{\frac{1.96^2}{2n}\pm 1.96\sqrt{\frac{1.96^2}{4n^2}}}{1+\frac{1.96^2}{n}}\Longrightarrow
\Big[0,\frac{1.96^2}{n+1.96^2}\Big]=\Big[0,\frac{3.84}{n+3.84}\Big]
\]</span>
Per exemple, un altre cop amb <span class="math inline">\(n=40\)</span></p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">binom.wilson</span>(<span class="dv">0</span>,<span class="dv">40</span>)</code></pre>
<pre><code>##   x  n proportion        lower     upper conf.level
## 1 0 40          0 6.330897e-18 0.0876216       0.95</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">qnorm</span>(<span class="fl">0.975</span>)<span class="op">^</span><span class="dv">2</span><span class="op">/</span>(<span class="dv">40</span><span class="op">+</span><span class="kw">qnorm</span>(<span class="fl">0.975</span>)<span class="op">^</span><span class="dv">2</span>)</code></pre>
<pre><code>## [1] 0.0876216</code></pre>
<p>Quan s’ha de calcular un interval de confiança del 95% per a una probabilitat <span class="math inline">\(p_X\)</span> a partir d’una mostra aleatòria simple on no hi ha hagut cap èxit, sovint es fa servir la regla següent:</p>
<blockquote>
<p><strong>Regla del 3:</strong> Quan en una mostra aleatòria simple de mida <span class="math inline">\(n\)</span> d’una variable aleatòria de Bernoulli de paràmetre <span class="math inline">\(p_X\)</span> no hi trobam cap èxit, un IC 95% per a <span class="math inline">\(p_X\)</span> va, aproximadament, de 0 a <span class="math inline">\(3/n\)</span>.</p>
</blockquote>
<p>Amb aquesta regla, en el nostre exemple amb <span class="math inline">\(n=40\)</span> obtendríem l’interval [0,3/40]=[0,0.075], no molt enfora del [0,0.088] que hem obtingut amb els altres dos mètodes.</p>
<p>Per veure com la regla del 3 aproxima l’interval de Clopper-Pearson, el gràfic següent mostra els valors <span class="math inline">\(3/n\)</span> i l’extrem superior de l’IC 95% de Clopper-Pearson a partir d’una mostra de mida <span class="math inline">\(n\)</span> amb 0 èxits:</p>
<pre class="sourceCode r"><code class="sourceCode r">f=<span class="cf">function</span>(n){<span class="kw">binom.exact</span>(<span class="dv">0</span>,n)<span class="op">$</span>upper}
<span class="kw">plot</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">100</span>,<span class="kw">sapply</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">100</span>,f),<span class="dt">pch=</span><span class="dv">20</span>,<span class="dt">cex=</span><span class="fl">0.7</span>,<span class="dt">xlab=</span><span class="st">&quot;n&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;Extrem superior&quot;</span>,
     <span class="dt">main=</span><span class="st">&quot;Extrem superior d&#39;un IC 95% en cas de 0 èxits&quot;</span>)
<span class="kw">curve</span>(<span class="dv">3</span><span class="op">/</span>x,<span class="dt">col=</span><span class="st">&quot;red&quot;</span>,<span class="dt">lwd=</span><span class="dv">2</span>,<span class="dt">add=</span><span class="ot">TRUE</span>)
<span class="kw">legend</span>(<span class="st">&quot;topright&quot;</span>,<span class="dt">lty=</span><span class="kw">c</span>(<span class="ot">NA</span>,<span class="dv">1</span>),<span class="dt">pch=</span><span class="kw">c</span>(<span class="dv">20</span>,<span class="ot">NA</span>),
       <span class="dt">legend=</span><span class="kw">c</span>(<span class="st">&quot;Clopper-Pearson&quot;</span>,<span class="st">&quot;Regla del 3&quot;</span>),<span class="dt">col=</span><span class="kw">c</span>(<span class="st">&quot;black&quot;</span>,<span class="st">&quot;red&quot;</span>),<span class="dt">cex=</span><span class="fl">0.7</span>)</code></pre>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-123-1.png" width="480" style="display: block; margin: auto;" /></p>
<p>El gràfic següent mostra els valors <span class="math inline">\(3/n\)</span> i els extrems superiors dels IC 95% de Clopper-Pearson i de Wilson a partir d’una mostra de mida <span class="math inline">\(n\)</span> (<span class="math inline">\(n\geqslant 40\)</span> per als IC de Wilson) amb 0 èxits:</p>
<pre class="sourceCode r"><code class="sourceCode r">f=<span class="cf">function</span>(n){<span class="kw">binom.exact</span>(<span class="dv">0</span>,n)<span class="op">$</span>upper}
<span class="kw">plot</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">100</span>,<span class="kw">sapply</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">100</span>,f),<span class="dt">pch=</span><span class="dv">20</span>,<span class="dt">cex=</span><span class="fl">0.5</span>,<span class="dt">xlab=</span><span class="st">&quot;n&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;Extrem superior&quot;</span>,
     <span class="dt">main=</span><span class="st">&quot;Extrem superior d&#39;un IC 95% en cas de 0 èxits&quot;</span>)
<span class="kw">curve</span>(<span class="dv">3</span><span class="op">/</span>x,<span class="dt">col=</span><span class="st">&quot;red&quot;</span>,<span class="dt">lwd=</span><span class="fl">1.5</span>,<span class="dt">add=</span><span class="ot">TRUE</span>)
<span class="kw">points</span>(<span class="dv">40</span><span class="op">:</span><span class="dv">100</span>,<span class="fl">3.84</span><span class="op">/</span>(<span class="dv">40</span><span class="op">:</span><span class="dv">100</span><span class="fl">+3.84</span>),<span class="dt">pch=</span><span class="dv">20</span>,<span class="dt">cex=</span><span class="fl">0.5</span>,<span class="dt">col=</span><span class="st">&quot;blue&quot;</span>)
<span class="kw">legend</span>(<span class="st">&quot;topright&quot;</span>,<span class="dt">lty=</span><span class="kw">c</span>(<span class="ot">NA</span>,<span class="ot">NA</span>,<span class="dv">1</span>),<span class="dt">pch=</span><span class="kw">c</span>(<span class="dv">20</span>,<span class="dv">20</span>,<span class="ot">NA</span>),
    <span class="dt">legend=</span><span class="kw">c</span>(<span class="st">&quot;Clopper-Pearson&quot;</span>,<span class="st">&quot;Wilson&quot;</span>,<span class="st">&quot;Regla del 3&quot;</span>),<span class="dt">col=</span><span class="kw">c</span>(<span class="st">&quot;black&quot;</span>,<span class="st">&quot;blue&quot;</span>,<span class="st">&quot;red&quot;</span>),<span class="dt">cex=</span><span class="fl">0.7</span>)</code></pre>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-124-1.png" width="480" style="display: block; margin: auto;" /></p>
<p>Els extrems superiors dels intervals de Clopper-Pearson i Wilson se superposen.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-125" class="example"><strong>Exemple 2.10  </strong></span>En un assaig d’un tractament de quimioteràpia, en una mostra de 100 pacients tractats, 25 desenvoluparen càncer testicular secundari. Volem calcular un IC 95% per a la proporció de pacients tractats amb aquesta quimioteràpia que desenvolupen càncer testicular.</p>
</div>

<p>En aquest cas podem emprar els tres mètodes:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">round</span>(<span class="kw">binom.exact</span>(<span class="dv">25</span>,<span class="dv">100</span>),<span class="dv">4</span>)</code></pre>
<pre><code>##    x   n proportion  lower  upper conf.level
## 1 25 100       0.25 0.1688 0.3466       0.95</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">round</span>(<span class="kw">binom.wilson</span>(<span class="dv">25</span>,<span class="dv">100</span>),<span class="dv">4</span>)</code></pre>
<pre><code>##    x   n proportion  lower upper conf.level
## 1 25 100       0.25 0.1755 0.343       0.95</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">round</span>(<span class="kw">binom.approx</span>(<span class="dv">25</span>,<span class="dv">100</span>),<span class="dv">4</span>)</code></pre>
<pre><code>##    x   n proportion  lower  upper conf.level
## 1 25 100       0.25 0.1651 0.3349       0.95</code></pre>
</div>
<div id="calcul-de-la-mida-de-la-mostra-per-a-fixar-lerror" class="section level3 unnumbered">
<h3>Càlcul de la mida de la mostra per a fixar l’error</h3>
<p>L’<strong>error</strong> de l’interval de confiança de Laplace és
<span class="math display">\[
M= z_{(q+1)/2} \sqrt{\frac{\widehat{p}_{X} (1-\widehat{p}_{X})}{n}}
\]</span>
No podem determinar la mida de la mostra a fi que l’interval de confiança tingui un error màxim sense conèixer <span class="math inline">\(\widehat{p}_{X}\)</span>, que no coneixem sense una mostra.</p>
<p>Però en el cas de l’interval de Laplace per a una proporció, podem donar un <span class="math inline">\(n\)</span> que garanteixi una amplada màxima donada valgui el que valgui <span class="math inline">\(\widehat{p}_{X}\in [0,1]\)</span>.</p>
<p>Fixau-vos que la funció <span class="math inline">\(y=p (1-p)\)</span>, amb <span class="math inline">\(p\in [0,1]\)</span>, és una paràbola còncava amb vèrtex al punt <span class="math inline">\(p=0.5\)</span></p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">curve</span>(x<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>x),<span class="dt">xlim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">1</span>),<span class="dt">xlab=</span><span class="st">&quot;p&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;&quot;</span>)
<span class="kw">abline</span>(<span class="dt">v=</span><span class="fl">0.5</span>,<span class="dt">lty=</span><span class="st">&quot;dashed&quot;</span>)</code></pre>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-127-1.png" width="480" style="display: block; margin: auto;" />
Per tant, el seu màxim s’assoleix a <span class="math inline">\(p=0.5\)</span>. Així, doncs
<span class="math display">\[
\widehat{p}_{X} (1-\widehat{p}_{X})\leqslant 0.5(1-0.5)=0.5^2\text{ per a tot $\widehat{p}_X\in[0,1]$}
\]</span>
i per tant
<span class="math display">\[
\begin{array}{l}
\displaystyle M=z_{(q+1)/2} \sqrt{\frac{\widehat{p}_{X} (1-\widehat{p}_{X})}{n}}\\
\qquad\displaystyle 
\leqslant z_{(q+1)/2}\sqrt{\frac{0.5^2}{n}}=\frac{0.5z_{(q+1)/2}}{\sqrt{n}}=\frac{z_{(q+1)/2}}{2\sqrt{n}}
\end{array}
\]</span></p>
<p>D’aquesta manera, si <span class="math inline">\(n\)</span> és tal que
<span class="math display">\[
\frac{z_{(q+1)/2}}{2\sqrt{n}}\leqslant M_{max}
\]</span>
aleshores <span class="math inline">\(M\leqslant M_{max}\)</span> segur, valgui el que valgui <span class="math inline">\(\widehat{p}_{X}\)</span>.</p>
<p>Per tant, el que farem serà calcular la <span class="math inline">\(n\)</span> per obtenir un error com a màxim <span class="math inline">\(M_{max}\)</span> <strong>en el cas més desfavorable</strong>: quan l’interval és el més ample possible, és a dir, suposant que <span class="math inline">\(\widehat{p}_{X}=0.5\)</span>:
<span class="math display">\[
M_{max}\geqslant\frac{z_{(q+1)/2}}{2\sqrt{n}}
\Rightarrow
n\geqslant\left(\frac{z_{(q+1)/2}}{2\cdot M_{max}}\right)^2
\]</span></p>
<p>En resum:</p>

<div class="theorem">
<p><span id="thm:unnamed-chunk-128" class="theorem"><strong>Teorema 2.7  </strong></span>Si <span class="math inline">\(n\geqslant\big(z_{(q+1)/2}/(2\cdot M_{max})\big)^2\)</span>, l’error de l’interval de Laplace calculat amb una mostra de mida <span class="math inline">\(n\)</span> sempre serà com a molt <span class="math inline">\(M_{max}\)</span>.</p>
</div>


<div class="example">
<p><span id="exm:unnamed-chunk-129" class="example"><strong>Exemple 2.11  </strong></span>Quina és la mida més petita d’una mostra que ens garanteixi un error de com a màxim 0.05 en estimar una proporció <span class="math inline">\(p_X\)</span> emprant un interval de confiança de Laplace del 95%?</p>
</div>

<p>Pel teorema anterior, per garantir un error de 0.05 en calcular un IC 95% per una proporció <span class="math inline">\(p_X\)</span> emprant la fórmula de Laplace, hem d’emprar una mostra de mida <span class="math inline">\(n\)</span> tal que
<span class="math display">\[
n\geqslant\Bigg(\frac{z_{(1+q)/2}}{2M_{max}}\Bigg)^2=\Bigg(\frac{1.96}{0.1}\Bigg)^2=384.16
\]</span></p>
<p>La mida més petita que satisfà aquesta condició és <span class="math inline">\(n=385\)</span>.</p>
<p>Observau tres coses:</p>
<ul>
<li><p>El valor de <span class="math inline">\(n\)</span> només depèn de la precisió i del nivell de confiança, no de la natura de l’estudi</p></li>
<li><p>Tal i com hem trobat la <span class="math inline">\(n\)</span>, estam segurs que si la mostra és com a mínim d’aquesta mida, l’interval de confiança de Laplace tendrà com a màxim una amplada <span class="math inline">\(2M_{max}\)</span>, sigui quina sigui la mostra. És de les poques vegades que podem estar segurs de qualque cosa en estadística.</p></li>
<li><p>El teorema anterio és per l’amplada de l’interval de Laplace, però la <span class="math inline">\(n\)</span> segurament us sortirà molt gran i en aquest cas l’interval de Laplace sol aproximar molt bé els altres dos intervals.</p></li>
</ul>
</div>
</div>
<div id="intervals-de-confianca-per-a-la-variancia-duna-variable-normal" class="section level2">
<h2><span class="header-section-number">2.5</span> Intervals de confiança per a la variància d’una variable normal</h2>
<p>Suposem que tenim una variable normal <span class="math inline">\(X\sim N(\mu,\sigma)\)</span>. Volem trobar un IC 95% per a la seva variància <span class="math inline">\(\sigma^2\)</span> (o la seva desviació típica <span class="math inline">\(\sigma\)</span>). Per calcular-lo, prenem una mostra aleatòria simple de mida <span class="math inline">\(n\)</span>, de variància mostral <span class="math inline">\(\widetilde{S}^2_X\)</span>.</p>
<p>Recordau que, en aquestes condicions
<span class="math display">\[
\frac{(n-1) \widetilde{S}_{X}^2}{\sigma^2}
\]</span>
té distribució <span class="math inline">\(\chi^2_{n-1}\)</span></p>
<p>Podem aprofitar aquest fet per obtenir intervals de confiança per a <span class="math inline">\(\sigma^2\)</span>:</p>

<div class="theorem">
<span id="thm:unnamed-chunk-130" class="theorem"><strong>Teorema 2.8  </strong></span>Si la variable <span class="math inline">\(X\)</span> és normal, un IC de nivell de confiança <span class="math inline">\(q\)</span> per a <span class="math inline">\(\sigma^2\)</span> és<br />
<span class="math display">\[
\left[ \frac{(n-1)\widetilde{S}_{X}^2}{\chi_{n-1,(1+q)/2}^2},
\frac{(n-1)\widetilde{S}_{X}^2}{\chi_{n-1,(1-q)/2}^2}
\right],
\]</span>
on <span class="math inline">\(\chi_{n-1,r}^2\)</span> és el <span class="math inline">\(r\)</span>-quantil de la distribució <span class="math inline">\(\chi_{n-1}^2\)</span>
</div>


<div class="rmdcorbes">
La justificació d’aquesta fórmula és la usual: com que
<span class="math display">\[
\begin{array}{l}
\displaystyle P(\chi_{n-1}^2\leqslant\chi_{n-1,(1-q)/2}^2)=\frac{1-q}{2}\\  
\displaystyle P(\chi_{n-1}^2\geqslant\chi_{n-1,(1+q)/2}^2)=\frac{1-q}{2},
\end{array}
\]</span>
tenim que
<span class="math display">\[
\begin{array}{l}
q=P\left(\chi_{n-1,(1-q)/2}^2\leqslant\chi_{n-1}^2\leqslant
\chi_{n-1,(1+q)/2}^2\right)\\[2ex]
\quad\displaystyle =P\left(\chi_{n-1,(1-q)/2}^2\leqslant\frac{(n-1) \widetilde{S}_{X}^2}{\sigma^2}\leqslant
\chi_{n-1,(1+q)/2}^2
\right)\\[2ex]
\quad\displaystyle = P\left(\frac{(n-1)
\widetilde{S}_{X}^2}{\chi_{n-1,(1+q)/2}^2}\leqslant\sigma^2\leqslant\frac{
(n-1)\widetilde{S}_{X}^2}{\chi_{n-1,(1-q)/2}^2}
\right)
\end{array}
\]</span>
</div>

<p>Fixau-vos que aquest interval de confiança per <span class="math inline">\(\sigma^2\)</span> no està centrat en <span class="math inline">\(\widetilde{S}_{X}^2\)</span>. A més, com que <span class="math inline">\(\chi_{n-1}^2\)</span> no és simètrica, s’han de calcularels dos quantils <span class="math inline">\(\chi_{n-1,(1-q)/2}^2\)</span> i <span class="math inline">\(\chi_{n-1,(1+q)/2}^2\)</span></p>

<div class="example">
<p><span id="exm:unnamed-chunk-132" class="example"><strong>Exemple 2.12  </strong></span>Un índex de qualitat d’un reactiu químic és el temps que triga a actuar. L’estàndard és que aquest ha de ser <span class="math inline">\(\leqslant 30\)</span> segons. Se suposa que la distribució del temps d’actuació del reactiu és aproximadament normal. Es realitzen 30 proves en les quals es mesura el temps
d’actuació del reactiu. Tenim els resultats guardats en el vector següent:</p>
</div>

<pre class="sourceCode r"><code class="sourceCode r">Temps=<span class="kw">c</span>(<span class="dv">12</span>,<span class="dv">13</span>,<span class="dv">13</span>,<span class="dv">14</span>,<span class="dv">14</span>,<span class="dv">14</span>,<span class="dv">15</span>,<span class="dv">15</span>,<span class="dv">16</span>,<span class="dv">17</span>,<span class="dv">17</span>,<span class="dv">18</span>,<span class="dv">18</span>,<span class="dv">19</span>,<span class="dv">19</span>,<span class="dv">25</span>,<span class="dv">25</span>,<span class="dv">26</span>,<span class="dv">27</span>,<span class="dv">30</span>,<span class="dv">33</span>,<span class="dv">34</span>,<span class="dv">35</span>,<span class="dv">40</span>,<span class="dv">40</span>,<span class="dv">51</span>,<span class="dv">51</span>,<span class="dv">58</span>,<span class="dv">59</span>,<span class="dv">83</span>)</code></pre>
<p>Volem calcular un interval de confiança per a la desviació típica <span class="math inline">\(\sigma\)</span> d’aquest temps d’actuació, amb nivell de confiança 95%. Com que la variable que ens dóna el temps és (aproximadament) normal, podem emprar la fórmula per a l’IC del 95% per a <span class="math inline">\(\sigma^2\)</span> anterior:
<span class="math display">\[
\left[ \frac{(n-1)\widetilde{S}_{X}^2}{\chi_{n-1,(1+q)/2}^2},
\frac{(n-1)\widetilde{S}_{X}^2}{\chi_{n-1,(1-q)/2}^2}
\right]
\]</span></p>
<p>on:</p>
<ul>
<li><span class="math inline">\(n=\)</span><code>length(Temps)</code><span class="math inline">\(=30\)</span></li>
<li><span class="math inline">\(\widetilde{S}_X^2=\)</span><code>var(Temps)</code><span class="math inline">\(=301.5505747\)</span></li>
<li><span class="math inline">\(q=0.95\)</span>, per tant <span class="math inline">\(\chi_{n-1,(1+q)/2}^2=\)</span><code>qchisq(0.975,29)</code><span class="math inline">\(=45.7222858\)</span> i <span class="math inline">\(\chi_{n-1,(1-q)/2}^2=\)</span><code>qchisq(0.025,29)</code><span class="math inline">\(=16.0470717\)</span></li>
</ul>
<p>Obtenim l’interval:
<span class="math display">\[
\left[ \frac{29\cdot 301.55}{45.72}, \frac{29\cdot 301.55}{16.05}\right]= [191.26, 544.96]
\]</span></p>
<p>Però aquest interval és per a la variància. Per obtenir un IC per a la desviació típica, prenem arrels quadrades dels extrems:
<span class="math display">\[
[\sqrt{191.26}, \sqrt{544.96}]=[13.83,23.34]
\]</span></p>

<div class="rmdcaution">
L’interval per a la variància basat en la distribució <span class="math inline">\(\chi^2\)</span> no és vàlid si la variable poblacional no és (aproximadament) normal. En aquest cas, el millor és emprar un mètode no paramètric, com per exemple el <em>bootstrap</em>.
</div>

</div>
<div id="poblacions-finites" class="section level2">
<h2><span class="header-section-number">2.6</span> “Poblacions finites”</h2>
<p>Fins ara hem emprat mostres aleatòries simples. Què passa si prenem mostres aleatòries sense reposició?</p>
<p>Si la mida <span class="math inline">\(N\)</span> de la població és molt més gran que la mida <span class="math inline">\(n\)</span> de la mostra (posem <span class="math inline">\(N\geqslant 1000n\)</span>), les fórmules donades fins ara funcionen (aproximadament) bé.</p>
<p>Quan la mida <span class="math inline">\(N\)</span> de la població <em>no</em> és molt més gran que la mida <span class="math inline">\(n\)</span> de la mostra, el que es fa és, a les fórmules que hem donat per als intervals de confiança per a <span class="math inline">\(\mu\)</span> o <span class="math inline">\(p_X\)</span>, multiplicar-hi l’error estàndard pel <em>factor de població finita</em>
<span class="math display">\[
\sqrt{\frac{N-n}{N-1}}
\]</span></p>
<p>Així:</p>
<ul>
<li><p>Si <span class="math inline">\(X\)</span> és una població de mida <span class="math inline">\(N\)</span> amb mitjana poblacional <span class="math inline">\(\mu\)</span> i prenem una mostra aleatòria sense reposició de <span class="math inline">\(X\)</span>, amb mitjana <span class="math inline">\(\overline{X}\)</span> i desviació típica mostral <span class="math inline">\(\widetilde{S}_X\)</span>, i si <span class="math inline">\(X\)</span> normal o si <span class="math inline">\(n\)</span> és gran, es recomana prendre com a IC de nivell de confiança <span class="math inline">\(q\)</span> per a <span class="math inline">\(\mu\)</span>
<span class="math display">\[
\overline{X}\pm t_{n,(q+1)/2}\frac{\widetilde{S}_X}{\sqrt{n}}\sqrt{\frac{\vphantom{(}N-n}{N-1}}
\]</span></p></li>
<li><p>Si <span class="math inline">\(X\)</span> una població de mida <span class="math inline">\(N\)</span> que segueix una distribució Bernoulli amb probabilitat d’èxit <span class="math inline">\(p_X\)</span> i prenem una mostra aleatòria sense reposició de <span class="math inline">\(X\)</span>, amb <span class="math inline">\(n\)</span> molt gran i nombres d’èxits i fracassos com a mínim 10, es recomana prendre com a IC de nivell de confiança <span class="math inline">\(q\)</span> per a <span class="math inline">\(p_X\)</span>
<span class="math display">\[
\widehat{p}_{X}\pm z_{(q+1)/2}\sqrt{\frac{\widehat{p}_{X}
(1-\widehat{p}_{X})}{n}}\sqrt{\frac{\vphantom{(}N-n}{N-1}}
\]</span></p></li>
<li><p>En les condicions del punt anterior, per obtenir un IC de nivell de confiança <span class="math inline">\(q\)</span> per a <span class="math inline">\(p_X\)</span> amb un marge d’error <span class="math inline">\(M_{max}\)</span> en el cas més desfavorable caldrà prendre una mostra de mida
<span class="math display">\[
n\geqslant\frac{Nz_{(q+1)/2}^2}{4M_{max}^2(N-1)+z_{(q+1)/2}^2}
\]</span></p></li>
</ul>

<div class="example">
<p><span id="exm:unnamed-chunk-135" class="example"><strong>Exemple 2.13  </strong></span>En una mostra aleatòria de 727 estudiants (diferents) de la UIB (<span class="math inline">\(N=12000\)</span>), 557 afirmàrem haver comès plagi en algun treball durant els seus estudis. Quin seria un interval de confiança del 95% per a la proporció <span class="math inline">\(p_X\)</span> d’estudiants de la UIB que han comès plagi en algun treball?</p>
</div>

<p>Una mostra de 727 estudiants diferents és molt gran respecte del total d’estudiants de la UIB, per la qual cosa convé emprar la fórmula de Laplace amb el factor de població finita
<span class="math display">\[
\widehat{p}_{X}\pm z_{(q+1)/2}\sqrt{\frac{\widehat{p}_{X}
(1-\widehat{p}_{X})}{n}}\sqrt{\frac{\vphantom{(}N-n}{N-1}}
\]</span>
on <span class="math inline">\(\widehat{p}_{X}=557/727=0.766\)</span>, <span class="math inline">\(z_{(q+1)/2}=1.96\)</span>, <span class="math inline">\(n=727\)</span> i <span class="math inline">\(N=12000\)</span>: dóna
<span class="math display">\[
0.766\pm \sqrt{\frac{0.766(1-0.766)}{727}}\sqrt{\frac{\vphantom{(}12000-727}{12000-1}}\Rightarrow [0.751,0.781]
\]</span>
Estimam amb un nivell de confiança del 95% que entre un 75.1 i un 78.1 dels estudiants de la UIB han comès plagi en algun treball.</p>

<div class="example">
<span id="exm:unnamed-chunk-136" class="example"><strong>Exemple 2.14  </strong></span>De quina mida hem de prendre una mostra aleatòria sense reposició d’estudiants de la UIB per estimar una proporció amb nivell de confiança del 95% i un marge d’error màxim de 0.05?
</div>

<p>Per la fórmula anterior (prenent <span class="math inline">\(N=12000\)</span> i <span class="math inline">\(z_{(1+q)/2}=1.96\)</span>), per garantir un marge d’error màxim de 0.05 cal prendre una mostra de mida
<span class="math display">\[
n\geqslant\frac{12000\cdot 1.96^2}{4\cdot 0.05^2(12000-1)+1.96^2}=372.3
\]</span>
Per tant, ens calen 373 estudiants.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="estimacio-puntual.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/cescrossello/Mates-II/edit/master/03-Intervals.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": ["Bioestadistica-II.pdf", "Bioestadistica-II.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
